# Generated by Django 3.0.7 on 2020-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200608_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='episode-1-wallpaper-16x9.jpg', upload_to='profiles/'),
        ),
    ]
